#http://localhost:8081/emp-rest/h2-console
#http://localhost:8081/emp-rest  ===> hal browser 
#http://localhost:8081/emp-rest/employees

##################### DEFAULT ##########################################################################
spring:
  application:
    name: RestEmployeeMgmApp
  profiles:
    active:
    - dev

---
##################### DEV ##########################################################################
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:employeedb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8081
  servlet:
    context-path: /emp-rest
  
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    mappings:
      enabled: true
      
      


---
##################### QA ##########################################################################     
spring:
  profiles: qa
  datasource:
    url: jdbc:h2:mem:employeedb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

server:
  port: 8082
  servlet:
    context-path: /emp-rest
  
      

